### ISSUE TITLE
Idea: Data Loss

### ISSUE THREAD

**Issue by Tykhostup** [open-science-promoters/RDM-promotion#10]
Narrator's voice: Once upon a time, in the kingdom of academia, there worked a scientist. S/he worked night and day to collect the best, most reliable data in his/her field. Months of hard work went by. Until one day an evil spell was cast upon the kingdom. All the the research data with no backup should be lost forever! 
"Why, oh why did I not backup my data?!" the researcher cried. 
All of a sudden, a data management fairy appeared. -lists data backup options-
And the scientist and his/her data lived happily ever after.

**Comment by jcolomb** [comment]
thanks I love the Data management fairy idea !

**Comment by jcolomb** [comment]
could you please also indicate how to publish the idea:

```
Your name: anonymous
Your orcid: NA
license to apply to your comment: CC0  CC-BY
your position at the time your life story happened: NA
```

**Comment by Tykhostup** [comment]
name: Olena Tykhostup
license to apply to the comment: CC0

**Comment by jcolomb** [comment]
on website
