### ISSUE TITLE
license for "TROLLing - why linguists need it" video

### ISSUE THREAD

**Issue by pdurbin** [open-science-promoters/RDM-promotion#15]
Over at https://gitter.im/mozillascience/community?at=5b72eb055762ee4fe575d97d @jcolomb asked me what the license for https://www.youtube.com/watch?v=uEf0c0NT9_A is but I don't know so I'm pinging @philippconzett and @oodu to ask. I believe we first saw it in 2015 during their lightning talk: https://projects.iq.harvard.edu/dataverse-community-meeting/agenda

I added the video to https://docs.google.com/spreadsheets/d/1ybqL2WNdJZb7nwEAJ6yWJ0W95D3CtyEkQ97DFcJydsk/edit?usp=sharing as instructed in the README for this git repo.

**Comment by philippconzett** [comment]
Thanks for asking! Strange we didn't add a license to this video. I have now suggested CC-BY to the creaters of the video, but I'm still waiting for some answers. I'll keep you posted :-)

**Comment by philippconzett** [comment]
The video is now licensed with CC-BY :-)
