### ISSUE TITLE
Video - researcher from Aerospace Engineering on benefits of Open Data

### ISSUE THREAD

**Issue by martateperek** [open-science-promoters/RDM-promotion#19]
Status: In github
Date: 24 August 2018
Your name: Submitted by Marta Teperek; person in the video - John-Alan Pascoe, 
Your orcid: 0000-0001-8520-5598
license to apply to your comment: CC-BY-NC-SA
your position at the time your life story happened: 
Input = video inspiration

Please enter your text here:
Link to the video: https://ocw.tudelft.nl/course-lectures/john-alan-pascoe-on-open-data/?course_id=26671
Video interview with John-Alan Pascoe from the Faculty of Aerospace Engineering at TU Delft talking about the benefits of Open Data. The video is part of a larger course Making Impact with Open Science created by TU Delft.

**Comment by jcolomb** [comment]
I have added the video to the list (googlesheet), I will look whether other videos of this series are of interest

**Comment by jcolomb** [comment]
this list of other videos are in #20
