### ISSUE TITLE
Why YOU need a data management plan - poster

### ISSUE THREAD

**Issue by martateperek** [open-science-promoters/RDM-promotion#21]
Status: In github
Date: 24/8/2018
Your name: Author: Peter Murray-Rust; Submitting person: Marta Teperek
Your orcid: NA
license to apply to your comment: CC-BY
your position at the time your life story happened: NA
Input = life story

https://blogs.ch.cam.ac.uk/pmr/2011/08/01/why-you-need-a-data-management-plan/

**Comment by jcolomb** [comment]
Thanks, this entry was already analysed,
I will check why the picture is not in the metadata file, though
